[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
mint_nft = "Df7dRn17zyZ2oJkHEEChMHNm5zoWhz3pfykrN3Wv7GM2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
